# Lab 03 - NumPy Library - Annette Bazan

- Numpy is an open-source Python Library that :
1. It was created in 2005
2. It operates on numerical data types
3. The core of NumPy are arrays
4. NumPy arrays are very similar to Python lists(one-dimensional); however, NumPy arrays are multi-dimensional and much faster in math operations on data(50 times faster than lists)
5. The name of NumPy arrays is "ndarray"(n-dimensional)
6. The best reliable source for NumPy is: https://numpy.org/

### Installing and Importing NumPy

In [1]:
# Let's install NumPy first
!pip install numpy

In [2]:
# Let's import NumPy
import numpy as np # np is an alias name for NumPy

In [3]:
# Let's check the version of the NumPy we have
print(np.__version__)

1.26.4


### Creating NumPy Arrays (ndarray) from Scratch

##### 1-D Arrays (one-dimensional)

In [4]:
# 1. Creating an array from a Python list
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [5]:
# Need to prove that it is an array not a Python list
type(a)

numpy.ndarray

In [6]:
# Let's create an array using a Python tuple
b = np.array((1, 2, 3, 4))
b

array([1, 2, 3, 4])

In [7]:
type(b)

numpy.ndarray

In [8]:
# An array that contains only zeros (int or float)
c = np.zeros(7, dtype=float)
c

array([0., 0., 0., 0., 0., 0., 0.])

In [9]:
# An array that contains only ones (int or float)
d = np.ones(7, dtype=int)
d

array([1, 1, 1, 1, 1, 1, 1])

In [10]:
# An array using the full() method creates a 2D
e = np.full((5,3),'Annette')
e

array([['Annette', 'Annette', 'Annette'],
       ['Annette', 'Annette', 'Annette'],
       ['Annette', 'Annette', 'Annette'],
       ['Annette', 'Annette', 'Annette'],
       ['Annette', 'Annette', 'Annette']], dtype='<U7')

In [11]:
e.ndim

2

In [12]:
# An array created by using the arange() method
f = np.arange(0, 12, 2)
f

array([ 0,  2,  4,  6,  8, 10])

In [13]:
# An array using random.randint
g = np.random.randint(9,size =5)
g

array([1, 8, 8, 5, 1])

In [14]:
# Proving the number of dimensions using a data attribute: extra information of an array/dataset
g.ndim

1

In [15]:
# Indexing an array
g[-2]

5

In [16]:
g[3]

5

In [17]:
# Slicing an array
g[:3]

array([1, 8, 8])

In [18]:
# Reversing the order of the elements
g[::-1]

array([1, 5, 8, 8, 1])

##### 2-D Arrays (two-dimensional)

In [19]:
# Let's create a 2-D array
h = np.random.randint(12,size = (4,6))
h

array([[ 6,  5, 10,  3,  7,  3],
       [ 4,  4,  5, 11, 11,  3],
       [ 0, 10,  4,  7,  4,  5],
       [10,  3,  0,  8,  4,  7]])

In [20]:
# Dimenstionality attribute
h.ndim

2

In [21]:
# Shape attribute
h.shape

(4, 6)

In [22]:
# The total number of values in h
h.size

24

In [23]:
# Indexing needs two points for rows and columns for a 2-D array
h[2,0]

0

In [24]:
# Slicing a 2-D array a range of rows and columns
h[1:4,1:5]

array([[ 4,  5, 11, 11],
       [10,  4,  7,  4],
       [ 3,  0,  8,  4]])

In [25]:
# Slicing on our own exercise
h[0:4,0:2]

array([[ 6,  5],
       [ 4,  4],
       [ 0, 10],
       [10,  3]])

##### 3-D Arrarys (theree-dimensional)

In [26]:
# Creating a 3-D array
i =np.random.randint(15,size=(4,4,5))
i

array([[[ 3,  4, 11, 12,  3],
        [ 9, 14,  8,  7, 13],
        [ 8, 11,  6, 12,  7],
        [ 3,  6,  8,  0,  7]],

       [[13, 13, 14,  4,  9],
        [13,  2,  0,  2, 14],
        [ 7, 14, 13,  0,  4],
        [ 3,  1,  7,  1,  7]],

       [[14,  7,  2,  9,  0],
        [13, 11,  9, 12,  4],
        [14,  4,  3,  2, 14],
        [ 1,  0,  2, 11,  2]],

       [[ 8,  4,  1,  2,  9],
        [10,  6, 14,  0,  4],
        [ 4,  0,  5, 14,  8],
        [ 0,  2,  6,  0,  0]]])

In [27]:
i.ndim

3

In [28]:
i.shape

(4, 4, 5)

In [29]:
i.size

80

In [31]:
# indexing a 3-D array first number is subset
i[2,3,2]

2

In [37]:
# slicing a 3-D array first number is subset, second numbers is rows, and third numbers are columns
i[2,:2,1:4]

array([[ 7,  2,  9],
       [11,  9, 12]])

In [38]:
# Creating a 4-D array
j = np.random.randint(10,size=(4,4,4,4))
j

array([[[[1, 8, 9, 5],
         [2, 1, 4, 7],
         [6, 4, 8, 7],
         [8, 4, 6, 6]],

        [[5, 2, 3, 1],
         [1, 5, 9, 5],
         [8, 2, 8, 9],
         [1, 4, 3, 5]],

        [[4, 3, 3, 5],
         [5, 9, 6, 1],
         [7, 5, 1, 1],
         [5, 9, 6, 2]],

        [[0, 5, 6, 7],
         [5, 2, 0, 6],
         [4, 5, 1, 2],
         [9, 4, 7, 3]]],


       [[[5, 7, 2, 5],
         [0, 7, 3, 3],
         [8, 0, 0, 9],
         [3, 9, 5, 1]],

        [[1, 7, 0, 7],
         [3, 9, 9, 0],
         [4, 9, 2, 7],
         [2, 1, 1, 8]],

        [[6, 6, 7, 4],
         [6, 9, 5, 1],
         [1, 6, 1, 9],
         [4, 7, 5, 6]],

        [[3, 4, 5, 8],
         [1, 0, 7, 8],
         [6, 8, 3, 4],
         [4, 9, 2, 8]]],


       [[[8, 6, 6, 3],
         [3, 6, 9, 4],
         [0, 1, 2, 0],
         [0, 5, 4, 7]],

        [[7, 4, 4, 1],
         [1, 2, 8, 8],
         [3, 4, 5, 3],
         [1, 6, 8, 8]],

        [[7, 5, 3, 0],
         [4, 7, 2, 0],
         [

**Observations:** Complete before submitting this lab
1. How many 3-D Arrays in i? 1
2. How many 2-D Arrays in i? 4
3. How many 1-D Arrays in i? 16
4. How many rows in i? 4
5. How many columns in i? 5
6. What is the shape of i? (4,4,5)
7. What is the dimensonality of i? 3-D
8. How many total values in i? 80 

### Arrays Concatenation: 

In [42]:
# Concatenation:adding 2 objects together (k + l) concatenate() method
k =np.array([[1,2,3],[4,5,6],[7,8,9]])
k

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
l = np.array([[10,11,12]])
l

array([[10, 11, 12]])

In [45]:
l.shape

(1, 3)

In [46]:
# Let's transpose l
l.T

array([[10],
       [11],
       [12]])

In [49]:
# Need to decide to add l as a row or column = #TypeError: only integer scalar arrays can be converted to a scalar index
# Adding l as a column
k_l = np.concatenate((k,l.T),axis=1)
k_l

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [51]:
# Adding l as a row doesn't need to be transposed because it was originally a row
k_l_1 = np.concatenate((k,l), axis = 0)
k_l_1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Array Splitting

In [52]:
m = np.array([10,20,30,40,50,60])
m

array([10, 20, 30, 40, 50, 60])

In [53]:
# Let's split m into 3 arrays
n = np.split(m,3)
n

[array([10, 20]), array([30, 40]), array([50, 60])]

### Arrary Sorting

In [56]:
o= np.array([9,7,3,5,1,8])

In [57]:
# Sorting a 1-D array
o1 =np.sort(o)
o1

array([1, 3, 5, 7, 8, 9])

In [59]:
# 2-D Sorting
p =np.array([[4,7,8],[6,2,5],[0,8,1]])
p

array([[4, 7, 8],
       [6, 2, 5],
       [0, 8, 1]])

In [61]:
# Let's sort a row: for sorting a row we use axis=1
p1 = np.sort(p,axis=1)
p1

array([[4, 7, 8],
       [2, 5, 6],
       [0, 1, 8]])

In [62]:
# Let's sort a column: for sorting a columns, we use axis=0
p2 = np.sort(p,axis=0)
p2

array([[0, 2, 1],
       [4, 7, 5],
       [6, 8, 8]])

### Conclusion:
1. Attributes help give more details to your datasets examples: shape, size, and dimensionality
2. A nested array is an array inside of an array so a sub array in the main array when speaking of dimensonality
3. Indexing an array is access a single element from its positon in square brackets and two points for rows and columns(x,y)
4. Slicing a 2-D array is a range of rows and columns you can use the colon(:) instead of 0 if its your begining point.
5. Size attribute is the total number of values, and shape is the numbers of rows and columns
6. When creating a 3-D arrary the first number is the number of subsets, second number is rows and the thrid number is columns
7. Transpose-changing the row and columns
8. Concatenation is adding two objects together make sure you are adding it as a row or column
9. 0 for rows 1 for columns, when adding l as a row it does not need to be transposed since it was originally a row
10. Every function/method when using NumPy make sure it starts with np
11. When sorting a multi-dimensional array use np.sort axis=1 is for rows and axis=0 is for columns
12. To sort rows we used axis = 1
13. To sort columns we used axis = 0
14. If there is a 3-D array it just means theres a 2-D inside of it and a 1D array as well
15. NumPy has random.randint which helps to generate random numbers to use in the dataset to help create an array

##### End of Lab 03