# Lab 04 -NumPy Universal Functions(ufuncs)-Annette Bazan

1. Arrays Aggregations (statistical summaries)
2. Arrays Broadcasting
3. Universal Functions (ufuncs)

### Arrays Aggregations (statistical summaries)

In [1]:
# Let's import needed libraries 
import numpy as np
import pandas as pd

In [2]:
a = np.array([3,6,7,9])
a

array([3, 6, 7, 9])

In [3]:
# Let's get the sum of a elements
b = np.sum(a)
b

25

In [4]:
#TypeError: add() takes from 2 to 3 positional arguments but 1 were given means add is a ufunc
# b_2 = np.add(a)
# b_2
type(np.add)

numpy.ufunc

In [5]:
# Let's get the average of a elements 
c = np.mean(a)
c

6.25

In [6]:
c_2 = np.average(a)
c_2

6.25

In [7]:
# To figure out the type of function and mean is also the same as average
type(np.average)

numpy._ArrayFunctionDispatcher

In [8]:
# Let's find the Maximum number in a elements
d = np.max(a)
d

9

In [9]:
# Let's find the Minimum in a elements
e = np.min(a)
e

3

In [10]:
# Let's find the median or middle number
f = np.array([2,4,8,9])
f_1 = np.median(f)
f_1
# 6 is not an element in the array but it is the median

6.0

In [11]:
# Let's find the standard deviation
g = np.std(a)
g

2.165063509461097

### Arrays Broadcasting
1. Broadcasting performs math operations more effectively and faster on **arrays with different shapes**
2. Broadcasting also uses the "vectorization" concept.

In [12]:
# 1. Broadcastin on 1-D array using a scaler(number)
h = np.array([4,6,9])
h

array([4, 6, 9])

In [13]:
# The scaler is 5 and it adds it to the array in h
h1 = h + 5
h1

array([ 9, 11, 14])

In [14]:
# The scaler is 2 and it is dedcuting from every element in h
h2 = h - 2
h2

array([2, 4, 7])

In [15]:
# Every element in h is multiplyed by 3(scaler) 
h3 = h * 3
h3

array([12, 18, 27])

In [16]:
# Every element in h is divided by 2(scaler) simple division
h4 = h / 2
h4

array([2. , 3. , 4.5])

In [17]:
# floor division, drops the remainder 
h5 = h // 2
h5

array([2, 3, 4], dtype=int32)

In [18]:
# 2. Broadcasting on arrays with different shapes
h6 = np.array ([[1],[2],[3]])
h6

array([[1],
       [2],
       [3]])

In [19]:
# rows and colums
h6.shape

(3, 1)

In [20]:
h7 = np.array([4,5,6])
h7

array([4, 5, 6])

In [21]:
h7.shape

(3,)

In [22]:
h6.ndim

2

In [23]:
h7.ndim

1

In [24]:
h8 = h6 + h7
h8

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

### NumPy Universal Functions (ufuncs)
1. Univerasal funcitons (ufuncs) are highly effective in performing math operations on arrays, by converting iterative objects into vectors.
2. Ufuncs also use the vectorization concept.

In [25]:
# Let's create x and y arrays
x = np.array([5,8,3,9])
x

array([5, 8, 3, 9])

In [26]:
y = np.array([2,6,7,4])
y

array([2, 6, 7, 4])

In [27]:
# Let's check out if a fucntion is ufunc or not
type(np.sum)

numpy._ArrayFunctionDispatcher

In [28]:
type(np.add)

numpy.ufunc

In [29]:
# 1. ufunc: addition
ufunc1 = np.add(x,y)
ufunc1

array([ 7, 14, 10, 13])

In [30]:
# 2. ufunc: subtraction
ufunc2 = np.subtract(y,x)
ufunc2

array([-3, -2,  4, -5])

In [31]:
# 2. ufunc: subtraction (order matters)
ufunc2_1 = np.subtract(x,y)
ufunc2_1

array([ 3,  2, -4,  5])

In [32]:
x

array([5, 8, 3, 9])

In [33]:
y

array([2, 6, 7, 4])

In [34]:
# 3. ufunc: multiplication 
ufunc3 = np.multiply(y,x)
ufunc3

array([10, 48, 21, 36])

In [35]:
# 4. ufunc: division
ufunc4 = np.divide(x,y)
ufunc4

array([2.5       , 1.33333333, 0.42857143, 2.25      ])

In [36]:
# 4. ufunc: divmod() 
ufunc4_1 = np.divmod(x,y)
ufunc4_1

(array([2, 1, 0, 2]), array([1, 2, 3, 1]))

In [37]:
# 5. ufunc: power() exponents
ufunc5 = np.power(x,y)
ufunc5

array([    25, 262144,   2187,   6561])

In [38]:
# 6. ufunc: remainder()  
ufunc6 = np.remainder(x,y)
ufunc6

array([1, 2, 3, 1])

In [39]:
# 6. ufunc: mod()  
ufunc6_1 = np.mod(x,y)
ufunc6_1

array([1, 2, 3, 1])

In [40]:
# 7. ufunc:absolute()
x1= np.array([8,-3,2,-5,-6])
ufunc7 =np.absolute(x1)
ufunc7

array([8, 3, 2, 5, 6])

In [41]:
# 8. ufunc: truncation:removing decimals : trunc()
y1 = np.array([-3.1666,2.457])
ufunc8 =np.trunc(y1)
ufunc8

array([-3.,  2.])

In [42]:
# 8. ufunc: fixed() 
ufunc8_1 = np.fix(y1)
ufunc8_1

array([-3.,  2.])

In [43]:
# 9. ufunc: around(): rounding decimals
ufunc9 = np.around(6.1666)
ufunc9

6.0

In [44]:
# 10.ufunc: floor(): rounding decimals( don't forget to enclose in square brackets for more than one value)
# rounding decimals to the nearest lower integer
ufunc10 = np.floor([6.1666,-2.444])
ufunc10

array([ 6., -3.])

In [45]:
# 11. ufunc: log2(): getting log based 2
x2 = np.array ([5,10,15])
ufunc11 = np.log2(x2)
ufunc11

array([2.32192809, 3.32192809, 3.9068906 ])

In [46]:
# 11. ufunc: log10(): getting log based 10
ufunc11_1 = np.log10(x2)
ufunc11_1

array([0.69897   , 1.        , 1.17609126])

In [47]:
# 12. ufunc: prod(): getting the product
ufunc12 = np.prod(x2)
ufunc12

750

In [48]:
# 12. ufunc: prod(): getting the product
x2 = np.array([5,10,15])
y2 = np.array([3,7,2])
ufunc12_1 = np.prod([x2,y2])
ufunc12_1

31500

In [49]:
# 13. ufunc: lcm(): lowest common multiple 
# reduce(): displays a single element 
x2 = np.array([5,10,15,18])
ufunc13 = np.lcm.reduce(x2)
ufunc13

90

In [50]:
# 14. ufunc: gcd(): greatest common divisor 
x2 = np.array([20,10,32,16])
ufunc14 = np.gcd.reduce(x2)
ufunc14

2

### Conclusions
1. Vector is 1-D
2. Matrix is 2-D
3. Matrix is lines that meet each other
4. Floor rounds to the nearest integer(lower)
5. Aggregation or statistical summaries mean, median,mode, average, sum, min, max,and standard deviation are all parts of array aggregation.
6. Array broadcasting advance perfomance of math with arrays that have different shapes.
7. Ufuncs uses vectorization as well as broadcasting. Using divmod() the first array is the quotient and the 2nd array is the remainder.
8. Vectorization is faster and more effiecent because it loops the code by making Python iterative objects
9. A vector is a line that doesnt meet
10. Don't forget to import NumPy and Pandas but since we installed those programs previously we don't have to do it everytime because it is also due to it be included in Anaconda.
11. To find the average you can use either np.mean or np.average both are numpy funcitons.
12. np.add is a ufunc and not a normal numpy function but np.sum is a regular function.
14. std is standard deviation which means the average of an elements then the distance of each element against the average.
15. Scaler is another word for just a plain number.
16. Overall it seems that broadcasting is just very efficent, fast and powerful in numpy that can perform math operations on arrays of any shape and dimensionality.

##### End of Lab 04